name: Create Branch and Pull Request

on:
  workflow_dispatch:
    inputs:
      workloadName:
        description: 'Name of the workload'
        required: true
        type: string
      serviceNowID:
        description: 'Service Now ID'
        required: true
        type: string

jobs:
  create-branch-and-pr:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
    
    env:
      NEW_BRANCH: workload/${{ inputs.workloadName }}_${{ inputs.serviceNowID }}
      NEW_DIRECTORY: workload_${{ inputs.workloadName }}_${{ inputs.serviceNowID }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Configure Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    
    - name: Create new branch and initial commit
      run: |
        git checkout -b ${{ env.NEW_BRANCH }}
        echo "# Initial commit from GitHub Actions" >> README.md
        mkdir ${{ env.NEW_DIRECTORY }}
        cp template/* ${{ env.NEW_DIRECTORY }}/
        git add .
        git commit -m "Initial commit for branch ${{ env.NEW_BRANCH }}"
    
    - name: Push new branch to remote
      run: |
        git push origin ${{ env.NEW_BRANCH }}
    
    - name: Create Pull Request
      run: |
        gh pr create \
          --title "Initial commit from GitHub Actions" \
          --body "This PR was automatically created by GitHub Actions workflow. It contains the initial commit for branch ${{ env.NEW_BRANCH }}." \
          --base main \
          --head ${{ env.NEW_BRANCH }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}