name: Create Branch and List Pull Requests

on:
  workflow_dispatch:

jobs:
  create-branch-and-list-prs:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: read
    
    env:
      NEW_BRANCH: feature/init-branch-${{ github.run_id }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Configure Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    
    - name: Create new branch and initial commit
      run: |
        git checkout -b ${{ env.NEW_BRANCH }}
        echo "# Initial commit from GitHub Actions" > README.md
        git add README.md
        git commit -m "Initial commit for branch ${{ env.NEW_BRANCH }}"
    
    - name: Push new branch to remote
      run: |
        git push origin ${{ env.NEW_BRANCH }}
    
    - name: List all pull requests using GitHub CLI
      run: |
        gh pr list --state all --json number,title,headRefName,baseRefName,author,state --template '{{range .}}{{.number}} | {{.title}} | {{.headRefName}} -> {{.baseRefName}} | {{.author.login}} | {{.state}}{{"\n"}}{{end}}'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: List PRs using GitHub REST API (alternative)
      run: |
        curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/pulls?state=all" \
          | jq -r '.[] | "\(.number) | \(.title) | \(.head.ref) -> \(.base.ref) | \(.user.login) | \(.state)"'